[package]
name = "ball-gfx-hal"
version = "0.1.0"
authors = ["Benjamin <benjamin@chronicembetterment.org>"]
edition = "2018"

[features]
default = ["renderdoc"]

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx", rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7" }
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx", rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7" }
imgui-gfx-hal = { git = "https://git.chronicembetterment.org/git/benjamin/imgui-gfx-hal" }
#imgui-gfx-hal = { path = "../imgui-gfx-hal" }
imgui = "0.0.21"
env_logger = "0.6.0"
winit = "0.17.0"
imgui-winit = "0.1.1"
log = "0.4.6"
renderdoc = { version = "0.4.0", optional = true }
cgmath = "0.16.1"
palette = "0.4.1"
rand = "0.6.0"
arrayvec = "0.4.7"
take_mut = "0.2.2"

[build-dependencies]
shaderc = "0.3.12"
walkdir = "2.2.7"
