[package]
name = "ball-gfx-hal"
version = "0.1.0"
authors = ["Benjamin <benjamin@chronicembetterment.org>"]
edition = "2018"

[features]
default = ["renderdoc"]

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx", rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7" }
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx", rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7" }
imgui-gfx-hal = { git = "https://git.chronicembetterment.org/git/benjamin/imgui-gfx-hal" }
#imgui-gfx-hal = { path = "../imgui-gfx-hal" }
imgui = "0.0.21"
env_logger = "0.6.0"
winit = "0.17.0"
imgui-winit = "0.1.1"
log = "0.4.6"
renderdoc = { version = "0.4.0", optional = true }
cgmath = { version = "0.16.1", features = ["serde"] }
palette = { version = "0.4.1", features = ["serde"] }
arrayvec = "0.4.7"
take_mut = "0.2.2"
parking_lot = "0.6.4"
bincode = "1.0.1"
serde = "1.0.80"
serde_derive = "1.0.80"
rand = "0.6.0"
failure = "0.1.3"
int_hash = "0.1.1"
mio = "0.6.16"
mio-extras = "2.0.5"
byteorder = "1.2.7"
crossbeam = "0.5.0"

[build-dependencies]
shaderc = "0.3.12"
walkdir = "2.2.7"
