[package]
name = "ball-gfx-hal"
version = "0.1.0"
authors = ["Benjamin <benjamin@chronicembetterment.org>"]
edition = "2018"

[features]
default = ["renderdoc"]

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx", rev = "a9986822ec6f679aff607b383126489e026d70f6" }
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx", rev = "a9986822ec6f679aff607b383126489e026d70f6" }
imgui-gfx-hal = { git = "https://git.chronicembetterment.org/git/benjamin/imgui-gfx-hal" }
#imgui-gfx-hal = { path = "../imgui-gfx-hal" }
imgui = "0.0.21"
winit = "0.18.0"
imgui-winit = "0.1.2"
log = { version = "0.4.6", features = ["max_level_trace", "release_max_level_info"] }
renderdoc = { version = "0.4.0", optional = true }
cgmath = { version = "0.16.1", features = ["serde"] }
palette = { version = "0.4.1", features = ["serde"] }
arrayvec = "0.4.8"
take_mut = "0.2.2"
parking_lot = "0.7.0"
bincode = "1.0.1"
serde = "1.0.80"
serde_derive = "1.0.80"
rand = "0.6.1"
failure = "0.1.3"
int_hash = "0.1.1"
mio = "0.6.16"
mio-extras = "2.0.5"
byteorder = "1.2.7"
structopt = "0.2.13"
ctrlc = "3.1.1"
lazy_static = "1.2.0"
colored = "1.6.1"

[build-dependencies]
shaderc = "0.3.12"
walkdir = "2.2.7"

[patch."https://github.com/gfx-rs/gfx"]
gfx-hal = { git = "https://github.com/Benjamin-L/gfx" }
gfx-backend-vulkan = { git = "https://github.com/Benjamin-L/gfx" }
