binop_separator = "Back"
combine_control_expr = false
condense_wildcard_suffixes = true
edition = "2018"
error_on_unformatted = false
force_multiline_blocks = true
format_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
skip_children = false
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
version = "One"
wrap_comments = true